pip._internal.exceptions.MetadataInvalid.__init__
2db2fa9d3ca6854ec78b71e3ee4a4c53