pip._internal.exceptions.MetadataInvalid.__str__
7e24cb99b7e84ec1e7e270eb9091a382