pip._internal.exceptions.DiagnosticPipError.__repr__
ea9c0ff3fd5ea70a12b2a48f3fda47ce