pip._internal.exceptions.MetadataGenerationFailed.__str__
4b5dfc9d80771dd78f7858809167f0ec