
1pip._vendor.urllib3.exceptions.LocationParseErrorm
a/home/kali/Documentos/API-de-X/env/lib/python3.12/site-packages/pip/_vendor/urllib3/exceptions.py° °("2*ò
2
¢ ¢(2a
_

¢ ¢(2
%2"__concat*%

¢ ¢('
Failed to parse: %s*

¢* ¢(2


locationC
A

¢ ¢(2	
message"__id*"

__unknown_file (

%2’“

£ £()
%3"type.__init__*)

__unknown_file (

	HTTPError*Q

__unknown_file (53
1pip._vendor.urllib3.exceptions.LocationParseError*'

__unknown_file (
	
message2__init__Å


• •( A3
1pip._vendor.urllib3.exceptions.LocationParseError"

location"__id*(

__unknown_file (


location*
3*k
3
exceptions.pyCA
® ®
%1"1pip._vendor.urllib3.exceptions.LocationParseError"
® ®

%1:

° °(

locationB53
1pip._vendor.urllib3.exceptions.LocationParseErrorH