
2pip._internal.exceptions.NoneMetadataError.__str__g
[/home/kali/Documentos/API-de-X/env/lib/python3.12/site-packages/pip/_internal/exceptions.pyó ó("2*¯
2
ö ö(Xy
w

ö ö()
%1"__id*]

__unknown_file (A*?,
*pip._internal.exceptions.NoneMetadataError"
metadata_namep
n

öM ö(V
%2"__id*T

__unknown_file (8*6,
*pip._internal.exceptions.NoneMetadataError"
distš
—

ö ö(X
%3"__concat*

ö ö(	
None *

ö ö()

%1*4

ö* ö(L&$
" metadata found for distribution: *

öM ö(V

%2"

ö ö(X

%3B.,
*pip._internal.exceptions.NoneMetadataErrorH